apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus-demo
    app.kubernetes.io/component: quarkus-demo
    app.kubernetes.io/instance: quarkus-demo
  name: quarkus-demo
  namespace: cjm-qtest
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: quarkus-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: quarkus-demo
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cjm-qtest/kenny:quarkus
        imagePullPolicy: Always
        name: quarkus-demo
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
