apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: quarkus-demo
spec:
  failedBuildsHistoryLimit: 1
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: quarkus-demo:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: main 
      uri: https://github.com/meidlinger/sdgdemoquarkus.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: openshift/Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 1
